### ISSUE TITLE
"Coral Cloud S3 Connection” not found in Other Connectors

### ISSUE THREAD

**Issue by sumi-akihi** [trailheadapps/coral-cloud#11]
## Problem
[Data Cloud deployment and configuration](https://github.com/trailheadapps/coral-cloud/blob/main/docs/data-cloud-setup.md)

“Coral Cloud S3 Connection” cannot be found under “Other Connections” in “Data Cloud Setup”, so I cannot configure the credentials for the Amazon S3 read-only connection.

![スクリーンショット 2024-10-20 午前8 49 48](https://github.com/user-attachments/assets/6fddf71e-4045-4396-bc36-936d1333b413)

But, I found it in the “Coral Cloud Data Kit - Sample App” stored in “Data Kits.”

![スクリーンショット 2024-10-20 午前8 52 46](https://github.com/user-attachments/assets/2bc9dc9e-fe1f-41e6-b5b8-6c877b660073)

Am I setting it up wrong somewhere? Or am I missing something?

**Comment by muenzpraeger** [comment]
@sumi-akihi, you can find the Data Cloud specific instructions in the docs [here](https://github.com/trailheadapps/coral-cloud/blob/main/docs/data-cloud-setup.md).

**Comment by sumi-akihi** [comment]
@muenzpraeger
I'm just reading the docs now. So I cannot it.
Where should I look?

**Comment by muenzpraeger** [comment]
@sumi-akihi It's not clear to me what you can't do. When you follow the instructions for Data Cloud the connection will be automatically set up, and you only have to fill in the credentials.

**Comment by sumi-akihi** [comment]
> 1. Install automatically some of the components (Amazon S3 connection and data streams) from the Data Kit thanks to the [Data Kit component deployment flow](https://developer.salesforce.com/docs/platform/data-cloud-dev/guide/dc-deploy_data_kit_components.html):
```bash
sf api request rest actions/custom/flow/sfdatakit__DeployDataKitComponents --method POST --body config/data-kit-deploy.json
```

First, this command fails.

**Comment by muenzpraeger** [comment]
@sumi-akihi Seems the CLI command changed - just commited a change to reflect the new command to launch the semi-automated Data Cloud setup.

**Comment by muenzpraeger** [comment]
@sumi-akihi Have you been able to complete this, or is this still open? TY

**Comment by sumi-akihi** [comment]
@muenzpraeger 
I have not solved the problem, but I will try again from the beginning.
So this issue can be closed.
thank you.
