### ISSUE TITLE
small typo in the readme

### ISSUE THREAD

**Issue by valon-loshaj** [trailheadapps/coral-cloud#26]
### Summary

when configuring the agent, the scope currently says: 
"Your job is to assist a Customer Service Representative support guests with questions about reservations and experiences they can book at the hotel." 

but is sounds like it should say: 
"Your job as a Customer Service Representative is to assist guests with questions about reservations and experiences they can book at the hotel."

### Salesforce Org Type

Trailhead Playground

### Steps To Reproduce

N/A

### Current Behavior

N/A

### Expected Behavior

N/A

### Relevant Log Output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muenzpraeger** [comment]
See PR comment.
