### ISSUE TITLE
Could not infer a metadata type error - when running sf project deploy start -d cc-employee-app

### ISSUE THREAD

**Issue by jillhertzman** [trailheadapps/coral-cloud#53]
### Summary

When following the instructions, at step 7 - Deploy the employee agent metadata.
I get the following error:

Error (1): C:\Users\jill\Documents\Code\coral-cloud\cc-employee-app\main\default\genAiFunctions\Check_Weather\Check_Weather.genAiFunction-meta.xml: Could not infer a metadata type

### Salesforce Org Type

Trailhead Playground

### Steps To Reproduce

@salesforce/cli/2.6.7 win32-x64 node-v18.15.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Hi @jillhertzman, thanks for reaching out. Please update to the latest SF CLI and let us know if the problem persists.

**Comment by jillhertzman** [comment]
@pozil work like a charm, thank you.
