### ISSUE TITLE
Getting error below on "sf project deploy start -d cc-employee-app" command after updating to latest CLI version

### ISSUE THREAD

**Issue by pcondonjr** [trailheadapps/coral-cloud#58]
### Summary

Flow                     │ Add_Experiences_to_Prompt                                     │ Your organization doesn't have    │             ││                          │                                                               │ permission to create flows of     │             ││                          │                                                               │ processType "PromptFlow".         │             ││ GenAiFunction            │ Check_Weather/Check_Weather                                   │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Check_Weather/input/schema                                    │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Check_Weather/output/schema                                   │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ Bot                      │ Copilot_for_Salesforce                                        │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiPlugin              │ Customer_Service_Assistant                                    │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiPlanner             │ EmployeeCopilotPlanner                                        │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ FlexiPage                │ Experience_Record_Page                                        │ generativePromptTemplate isn’t a  │             ││                          │                                                               │ valid property name.              │             ││ Flow                     │ Experiences_Loop                                              │ Your organization doesn't have    │             ││                          │                                                               │ permission to create flows of     │             ││                          │                                                               │ processType "PromptFlow".         │             ││ GenAiPromptTemplate      │ Generate_Experience_Description                               │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiPromptTemplate      │ Generate_Guest_Reviews_Summary                                │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiPromptTemplate      │ Generate_Personalized_Schedule                                │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Generate_Personalized_Schedule/Generate_Personalized_Schedule │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Generate_Personalized_Schedule/input/schema                   │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Generate_Personalized_Schedule/output/schema                  │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiPromptTemplate      │ Generate_Social_Media_Posts                                   │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Issue_Bulk_Resort_Credits/Issue_Bulk_Resort_Credits           │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Issue_Bulk_Resort_Credits/input/schema                        │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Issue_Bulk_Resort_Credits/output/schema                       │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Issue_Resort_Credit/Issue_Resort_Credit                       │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Issue_Resort_Credit/input/schema                              │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Issue_Resort_Credit/output/schema                             │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ Flow                     │ PersonalizedSchedule                                          │ Invoke_Prompt (Action) - We can't │             ││                          │                                                               │ find an action with the name and  │             ││                          │                                                               │ action type that you specified.   │             ││ GenAiPromptTemplate      │ Policy_Questions                                              │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Policy_Questions/Policy_Questions                             │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Policy_Questions/input/schema                                 │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ GenAiFunction            │ Policy_Questions/output/schema                                │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ ApexClass                │ SocialMediaPostsController                                    │ Type is not visible:              │ 21:92       ││                          │                                                               │ ConnectApi.EinsteinLLM (21:92)    │             ││ GenAiPromptTemplate      │ Welcome_Email_for_Upcoming_Trip                               │ Not available for deploy for this │             ││                          │                                                               │ organization                      │             ││ LightningComponentBundle │ generateSocialMediaPosts                                      │ Unable to find Apex action class  │             ││                          │                                                               │ referenced as                     │             ││                          │                                                               │ 'SocialMediaPostsController'.     │             │└──────────────────────────┴───────────────────────────────────────────────────────────────┴───────────────────────────────────┴─────────────┘

Warning: GenAiFunction, Policy_Questions/output/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Issue_Bulk_Resort_Credits/input/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Check_Weather/Check_Weather, returned from org, but not found in the local project
Warning: GenAiFunction, Generate_Personalized_Schedule/input/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Issue_Resort_Credit/input/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Generate_Personalized_Schedule/Generate_Personalized_Schedule, returned from org, but not found in the local project  
Warning: GenAiFunction, Issue_Bulk_Resort_Credits/Issue_Bulk_Resort_Credits, returned from org, but not found in the local project
Warning: GenAiFunction, Issue_Resort_Credit/Issue_Resort_Credit, returned from org, but not found in the local project
Warning: GenAiFunction, Issue_Resort_Credit/output/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Policy_Questions/input/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Check_Weather/input/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Generate_Personalized_Schedule/output/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Policy_Questions/Policy_Questions, returned from org, but not found in the local project
Warning: GenAiFunction, Check_Weather/output/schema, returned from org, but not found in the local project
Warning: GenAiFunction, Issue_Bulk_Resort_Credits/output/schema, returned from org, but not found in the local project

### Salesforce Org Type

Trailhead Playground

### Steps To Reproduce

sf project deploy start -d cc-employee-app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muenzpraeger** [comment]
Can you check if you enabled the Einstein features as outlines in step 1 of
the README.

**Comment by pcondonjr** [comment]
@muenzpraeger I apologize for not following instructions! Thank you for your help

**Comment by muenzpraeger** [comment]
No worries. I ran into this myself before. 🎯
