### ISSUE TITLE
Failure during installation

### ISSUE THREAD

**Issue by ygavrylenko** [trailheadapps/coral-cloud#9]
All components seem to get installed properly but one fails - all other features are enabled in the org.

`
Component Failures [1]
============================================================================================================================
| Type  Name                   Problem                                                                           Line:Column 
| ───── ────────────────────── ───────────────────────────────────────────────────────────────────────────────── ─────────── 
| Error EmployeeCopilotPlanner common.exception.SfdcSqlException: ; nested exception is:                                     
|                              	common.exception.ApiQueryException:                                                           
|                              GenAiPlannerFunctionDef WHERE Id in ('17DJ9000000TN1j,17DJ9000000TN1k')                       
|                                                            ^                                                               
|                              ERROR at Row:1:Column:54                                                                      
|                              invalid ID field: 17DJ9000000TN1j,17DJ9000000TN1k; [conn=STANDARD:4:4:1854:44257]  `

**Comment by muenzpraeger** [comment]
Added workaround instructions to README until product fix will be deployed.
